//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAccounting_Client.Assets.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public int id { get; set; }
        public Nullable<int> owner_id { get; set; }
        public Nullable<int> goal_id { get; set; }
        public string source { get; set; }
        public Nullable<bool> is_income { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string commentary { get; set; }
    
        public virtual member member { get; set; }
    }
}
